version: '3.4'

services:
  nodetodo:
    image: nodetodo
    build: . 
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    restart: always
    links:
      - "mongo"
  mongo:
   image: mongo:latest
   ports:
     - "27017:27017"
   volumes:
     - data:/data/db
   
volumes:
  data:


